package com.glacialrush.game.event;

public enum ExperienceType
{
	UNKNOWN,
	KILL,
	KILL_HIGH_THREAT,
	KILL_BONUS,
	KILL_ASSIST,
	KILL_ASSIST_BONUS,
	KILL_ASSIST_HIGH_THREAT,
	POINT_CONTROL,
	TERRITORY_CONTROL
}
