name: GlacialServer
main: com.glacialrush.GlacialServer
version: 1.0
depend: [GlacialAPI]
commands:
  region:
    aliases: [r, reg, rg]
  map:
    aliases: [m, mp]
  game:
    aliases: [g, gme]
  brush:
    aliases: [b, br]