name: GlacialServer
main: com.glacialrush.server.GlacialServer
version: 1.0
depend: [GlacialAPI]
commands:
  region:
    aliases: [reg, rg]
  map:
    aliases: [m, mp]
  game:
    aliases: [g, gme]
  brush:
    aliases: [b, br, bruh]
  language:
    aliases: [lang, l, lng, la]
  teleport:
    aliases: [tp]
  teleporthere:
    aliases: [tphere, tph]
  sun:
    aliases: [sunny]
  leave:
    aliases: [quit, q, qqq, qq, rq, ragequit]
  rain:
    aliases: [snow, downfall]
  day:
    aliases: [norain, clearsky]
  night:
    aliases: [nightfall]
  message:
    aliases: [msg, pm]
  reply:
    aliases: [r]
  gamemode:
    aliases: [gamemode]
  gamemodec:
    aliases: [gmc]
  gamemodea:
    aliases: [gma]
  gamemodes:
    aliases: [gms]